[profile.default]
src     = "src"
out     = "out"
libs    = ["lib"]
test    = "test"
script  = "script"
cache   = true

# Solidity compiler
solc            = "0.8.24"
optimizer       = true
optimizer_runs  = 200
fs_permissions  = [{ access = "read", path = "src/" }]
# --------------------------------------------------------------------------
# Remappings
# --------------------------------------------------------------------------
remappings = [
    "forge-std/=lib/forge-std/src/",
]

# --------------------------------------------------------------------------
# RPC endpoints (use with --rpc-url <name>)
# --------------------------------------------------------------------------
[rpc_endpoints]
anvil     = "http://127.0.0.1:8545"
fuji      = "https://api.avax-test.network/ext/bc/C/rpc"
avalanche = "https://api.avax.network/ext/bc/C/rpc"

# --------------------------------------------------------------------------
# Block explorer verification
# --------------------------------------------------------------------------
[etherscan]
fuji = { key = "verifyContract", url = "https://api.routescan.io/v2/network/testnet/evm/43113/etherscan", chain = 43113 }
avalanche = { key = "verifyContract", url = "https://api.routescan.io/v2/network/mainnet/evm/43114/etherscan", chain = 43114 }

# --------------------------------------------------------------------------
# Fuzz testing
# --------------------------------------------------------------------------
[fuzz]
runs = 256
